import React, { useState } from 'react';
import Board from './Board';
import {ROOK_BLACK,ROOK_WHITE,BISHOP_BLACK,BISHOP_WHITE,PAWN_BLACK,PAWN_WHITE,KING_BLACK,KING_WHITE,QUEEN_BLACK,QUEEN_WHITE,KNIGHT_BLACK,KNIGHT_WHITE}  from "./utils.js"
function Chess() {
    const EMPTY = 0;
    const BOARD_SIZE = 8;
    
    const [board,setBoard] = useState(
        [
        
        [ROOK_BLACK, KNIGHT_BLACK, BISHOP_BLACK, KING_BLACK, QUEEN_BLACK, BISHOP_BLACK, KNIGHT_BLACK, ROOK_BLACK],
        [PAWN_BLACK, PAWN_BLACK, PAWN_BLACK, PAWN_BLACK, PAWN_BLACK, PAWN_BLACK, PAWN_BLACK, PAWN_BLACK],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [PAWN_WHITE, PAWN_WHITE, PAWN_WHITE, PAWN_WHITE, PAWN_WHITE, PAWN_WHITE, PAWN_WHITE, PAWN_WHITE],
        [ROOK_WHITE, KNIGHT_WHITE, BISHOP_WHITE, QUEEN_WHITE, KING_WHITE, BISHOP_WHITE, KNIGHT_WHITE, ROOK_WHITE],
      ]);
    
    return (
        <div><Board board={board} /></div>
    )
}

export default Chess ;